export const GET_CURRENT_NETWORK = "GET_CURRENT_NETWORK";
export const INIT_APP = "INIT_APP";
export const CREATE_SELL_CONTRACT = "CREATE_SELL_CONTRACT";
export const CREATE_USER = "CREATE_USER";
export const LIST_PUBLICATION = "LIST_PUBLICATION";