export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_CURRENT_NETWORK = "SET_CURRENT_NETWORK";
export const SET_ETHERSCAN_NETWORK = "SET_ETHERSCAN_NETWORK";
export const SET_WEB3 = "SET_WEB3";
export const SET_NUMBER_OF_PUBLICATIONS = "SET_NUMBER_OF_PUBLICATIONS";
export const SET_ALL_LISTED_PUBLICATIONS = "SET_ALL_LISTED_PUBLICATIONS"
export const SET_CONTRACT_ADDRESS = "SET_CONTRACT_ADDRESS"
export const SET_USER_NUMBER = "SET_USER_NUMBER"